### ISSUE TITLE
Unroll sum and / or dot manually so that it autovectorizes

### ISSUE THREAD

**Issue by bluss** [bjz/cgmath#280]
Edit: Oops! This lib doesn't have arbitrary length vectors, only nalgebra has that. But they are not as responsive..

See this pattern for how to write a float reduce loop so that it can autovectorize:

Implementation in ndarray: [unroll_sum](https://github.com/bluss/rust-ndarray/blob/6a77a16ba11d4697a36c89dbd1ca8479e78ee9c9/src/lib.rs#L1869-L1900)

Same pattern for dot product: [user forum post](https://users.rust-lang.org/t/how-to-zip-two-slices-efficiently/2048/12)

It's not super pretty, and it hardcodes the number of lanes used, but it's still much faster for floats than the naive sum since llvm can not vectorize that. (rust-lang/rust/issues/21690 would be needed).

**Comment by bjz** [comment]
Nice! Even though we don't have ND vectors, we should check to see that these are optimised correctly for our current types.

**Comment by bjz** [comment]
Closing, because this does not apply to us. ;)
