### ISSUE TITLE
Serde serialization support

### ISSUE THREAD

**Issue by NeoLegends** [bjz/cgmath#313]
As a Rust-newbie coming from C# I've found `RustcSerializable` and `RustcDeserializable` are very hard to use (seems like I'm prone to [this](http://stackoverflow.com/questions/27650643/how-do-i-fix-encodable-decodable-deprecation) error), my program does very much depend on serialization though.

Switching to Serde fixed my compiler problems and also seems to be the de-facto new way of doing serialization in Rust according to [this](https://users.rust-lang.org/t/whats-up-with-rustc-serialize/589) and [this](https://www.reddit.com/r/rust/comments/3v4ktz/differences_between_serde_and_rustc_serialize/). Automatically deriving Serde implementations in my code doesn't work though, since this library is built upon `rustc-serialize`. 
So what do you think about incorporating Serde support into this library (while possibly retaining rustc-serialize support via Cargo.toml and #cfg)? I'm happy to file a PR once somebody approves this.

**Comment by bjz** [comment]
It seems like lots of libraries have the option to use Serde vs rustc-serialize using features... not sure how t would affect dependecy chains though :/

**Comment by bjz** [comment]
The issue with dependencies is this: what if one library uses the rustc-serialize feature, where as another uses Serde? Is there a normal way to handle this?

cc. @erickt

**Comment by mitchmindtree** [comment]
@bjz I'm about to have a go at adding support for serde to my RustAudio crates by doing manual implementations (will either make or use an existing `macro_rules` to help) in a feature-gated `serde.rs` module in each crate that requires it.

It seems to me like serialisation (whether serde or/and rustc-serialize) is the perfect thing to put behind a feature gate for crates like this, but it would be good to get some more opinions!

**Comment by NeoLegends** [comment]
@bjz Couldn't we enable rustc-serialize and serde at the same time?

**Comment by erickt** [comment]
@bjz: serde and rustc-serialize are orthogonal to each other. You can use both at the same time. It's pretty simple to put both behind feature flags and request those features to be enabled in a dependency.

**Comment by bjz** [comment]
@NeoLegends: I definitely be open to looking at a pull request that enables this support.
