### ISSUE TITLE
Feature request: cgmath::BaseFloat provides access to float methods from f32 and f64

### ISSUE THREAD

**Issue by mhintz** [bjz/cgmath#319]
My specific use case is implementing an arcball-style camera for cgmath to use in a project I'm working on. (https://github.com/mhintz/arcball-cgmath). I initially tried to make the struct generic over `<T: cgmath::BaseFloat>` so that it could use f32 and f64, but with only that trait bound I can't use float methods like `.acos`, `.min`, and `.max`. The rustc error is "error: source trait is private".

I'm not really sure what to make of this, to be honest. Looking at the cgmath source I can't put my finger on what the issue is. I wish I knew more and could propose a fix

**Comment by bjz** [comment]
You need to import `Float` from `rust_num` to use these methods. It's my fault for not having any examples for this. I would like to remove the dependency on `rust_num` to be honest - having to import `BaseFloat` _and_ `Float` is pretty ugly.

**Comment by mhintz** [comment]
Ok, awesome! I got it working, thanks for your help.

(For anyone looking for how to make structs that use cgmath generic over floating point types, see https://github.com/mhintz/arcball-cgmath).

The only pain point is using floating point primitive literals aside from zero and one, which are provided by trait functions. Is there a better way to make literals generic than this?
`num::NumCast::from(5.0).unwrap()`

cheers!

**Comment by bjz** [comment]
Yeah, `cast` is ugly, and annoying, even within cgmath itself. This is why I'm thinking we should cut our ties with `rust_num`. Lots of `rust_num` is a dumping ground for our past failures with regards to making a numeric hierachy for Rust, and there hasn't been much work on improving its ergonomics.
