### ISSUE TITLE
Add rotation constructors to Matrix4

### ISSUE THREAD

**Issue by bjz** [bjz/cgmath#324]
`Matrix4` doesn't currently implement methods like `from_euler` etc...

**Comment by mhintz** [comment]
I suppose, in addition to the From<Euler> impl for Matrix4, this issue needs from_angle_x, from_angle_y, from_angle_z, and from_axis_angle?

Anything I'm forgetting?

**Comment by bjz** [comment]
Fixed by #348 ❤️
