### ISSUE TITLE
Is there a reason why Transform3 isn't implemented for Matrix4?

### ISSUE THREAD

**Issue by mhintz** [bjz/cgmath#337]
Currently, as far as I know the only way to transform a Point3 with a Matrix4 is:

```rust
Pt::from_vec((transform * pt.to_homogeneous()).truncate())
```

But there's a perfectly good API for objects which can transform points, `Transform3`.

This would be useful for procedural geometry generation applications, where you want to produce vertices for the same shape, translated and rotated to your desired location.

**Comment by kvark** [comment]
Related - https://github.com/bjz/cgmath/pull/302#issuecomment-211168768

**Comment by bjz** [comment]
Agreed.

**Comment by bjz** [comment]
The original reason, as mentioned in the thread that @kvark linked to, was that it requires additional interpretation of a matrix to treat it as an affine transformation vs a rotation. I think that I need to revise this stance though, for simplicity.

**Comment by bjz** [comment]
Related: #324

**Comment by bjz** [comment]
I'm guessing we would have to incorporate `One` (and `Zero` for completeness) into the trait hierarchy to avoid collisions. `concat` would then become `mul`.

**Comment by mhintz** [comment]
Stuff like this hurts the usability of cgmath for me. I just want to be able to make quaternions, matrices, and vectors, and have them all play nice with each other in the expected ways.

**Comment by bjz** [comment]
Closing in favor of #349
