### ISSUE TITLE
Discrepancy between docs and code in v0.10.0

### ISSUE THREAD

**Issue by iwburns** [bjz/cgmath#363]
Noticed that one(), concat(), concat_self(), and invert_self() are no longer present in the Rotation trait but they are listed as present in the docs.

Maybe the docs need to be updated/re-generated?

**Comment by bjz** [comment]
Ah, this is because I forgot to push to the `stable` branch! That's what gets published to gh-pages.

**Comment by bjz** [comment]
Just pushed - should be fixed soon.

**Comment by iwburns** [comment]
At work now, but I'll check it out when I get a minute.  Thanks for looking into this!

**Comment by bjz** [comment]
Looks good to me now! Let me know if you are still having trouble.

**Comment by iwburns** [comment]
Looks good to me as well.  Thanks again!
